### ISSUE TITLE
Won't build on FreeBSD clang 4.0

### ISSUE THREAD

**Issue by mike402** [TRIQS/cthyb#86]
[ 15%] Building CXX object c++/CMakeFiles/cthyb_c.dir/impurity_trace.cpp.o                                                                                    
    In file included from /home/md/src/git/cthyb/c++/impurity_trace.cpp:21:                                                                                       
    In file included from /home/md/src/git/cthyb/c++/impurity_trace.hpp:25:                                                                                       
    /home/md/src/git/cthyb/c++/triqs/utility/rbt.hpp:664:7: error: expected member name or ';' after declaration specifiers                                       
     void _assert(bool c) const {                                                                                                                                 
     ~~~~ ^                                                                                                                                                       
    /usr/include/assert.h:50:22: note: expanded from macro '_assert'                                                                                              
    #define _assert(e)      ((void)0)                                                                                                                             
                              ^

**Comment by krivenko** [comment]
Hi Mike,

Could you please post your CMake output? Also, what branch of cthyb are you trying to use (`master` or `unstable`)?

**Comment by mike402** [comment]
Hi,

Using master.

Should I post CMakeCache.txt?

**Comment by krivenko** [comment]
Nevermind, I can already see the problem.
There is a name collision between `triqs::utility::rb_tree::_assert()` and a macro that is apparently defined in `/usr/include/assert.h` on FreeBSD.

@HugoStrand Can we just get rid of that `_assert()` method? It does not really make sense...

**Comment by mike402** [comment]
Yes, I've actually made it compile by renaming that method there now.

**Comment by HugoStrand** [comment]
Dear Mike,

Thank you for reporting the problem, I have renamed the assert in commit ad511782cfa71fe on the `unstable` branch. Please reopen this issue if that does not fix the problem.

Best regards,
Hugo

**Comment by mike402** [comment]
Thank you, it builds alright!
